remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: LLM4HW
description: Large Language Models for Hardware Design
show_downloads: false
logo: /assets/images/llm4hw-logo.png